#!/usr/bin/env bash

activewindow=""

activewindow_event() {
	activewindow=$1
}

generate() {
	echo '{ "current": "'"$activewindow"'" }'
}

# main loop
socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | rg --line-buffered "activewindow" | while read -r line; do
  case ${line%>>*} in
    "activewindow")
	  activewindow_event "${line#*,}"
      ;;
  esac
  generate
done
