#!/usr/bin/env bash

get_status() {
  s=$1
  if [ "$s" = "Playing" ]; then
    echo ""
  else
    echo ""
  fi
}

get_length_sec() {
  len=$1
  if [ -z "$len" ]; then
    echo 0
  else
    bc <<<"$len / 1000000"
  fi
}

get_length_time() {
  len=$1
  if [ -n "$len" ]; then
    len=$(bc <<<"$len / 1000000 + 1")
    date -d@"$len" +%M:%S
  else
    echo ""
  fi
}

get_position() {
  pos=$1
  len=$2
  if [ -n "$pos" ]; then
    bc -l <<<"$pos / $len * 100"
  else
    echo 0
  fi
}

get_position_time() {
  pos=$1
  len=$2
  if [ -n "$pos" ]; then
    date -d@"$(bc <<<"$pos / 1000000")" +%M:%S
  else
    echo ""
  fi
}

sanitize() {
  echo "$1" | sed 's/"/\"/g'
}

playerctl -F metadata -f '{{title}}\{{artist}}\{{status}}\{{position}}\{{mpris:length}}\{{mpris:artUrl}}' 2>/dev/null | while IFS="$(printf '\')" read -r title artist status position len; do
  jq --null-input -r -c \
    --arg artist "$(sanitize "$artist")" \
    --arg title "$(sanitize "$title")" \
    --arg status "$(get_status "$status")" \
    --arg pos "$(get_position "$position" "$len")" \
    --arg pos_time "$(get_position_time "$position" "$len")" \
    --arg length "$(get_length_time "$len")" \
    '{"artist": $artist, "title": $title, "status": $status, "position": $pos, "position_time": $pos_time, "length": $length}'
done