#!/usr/bin/env bash

vol() {
  wpctl get-volume @DEFAULT_AUDIO_"$1"@ | awk '{print int($2*100)}'
}

ismuted() {
  wpctl get-volume @DEFAULT_AUDIO_"$1"@ | rg -i muted
}

printVolume() {
	# echo '{
	#  "input": {
	#    "volume": "'"$(vol "SOURCE")"'",
	#    "muted": "'"$(ismuted "SOURCE")"'"
	#  },
	#  "output": {
	#    "volume": "'"$(vol "SINK")"'",
	#    "muted": "'"$(ismuted "SINK")"'"
	#  }
	# }'

	echo "{ \"input\": { \"volume\": \""$(vol "SOURCE")"\", \"muted\": \""$(ismuted "SOURCE")"\" }, \"output\": { \"volume\": \""$(vol "SINK")"\", \"muted\": \""$(ismuted "SINK")"\" }}"
}

printVolume
stdbuf -o0 alsactl monitor | \
  while read; do
    printVolume
  done

